[Server] #账号与密码,支持多账号进行抢课
username = [""]#(必填)
password = [""]#(必填)

[Mode]
Number = "single" # 单人抢课模式：single 多账号抢课模式：multiple (必填)
Select = ["Start","End"] #抢课模式： "Start" 候选模式： "End"，支持同时开启两种模式 (必填)

[Plan]#你要选的课程，确保课程名称、老师名称、时间、星期都正确
#可自行在中括号中添加中括号
Course_name = ["课程1","课程2","课程3"] # 课程名字,可以填多个(必填)

#选择顺序
#0:必修选课 1：选修选课 2：本学期计划内选课 3：专业内跨年级选课 4：计划外选课 5：公选课选课 6：辅修选课
#默认顺序： 1->2->3->4->5->6
#示例[["2","3",""],["2",""],[""]]
Course_order = [[],[],[]] # 课程选择顺序，如果你知道你选择的课程在本学期计划内，或专业内跨年级等，就在子列表中填入顺序，程序会按顺序进行查找课程，或者说你并不确定，那就留一个空字符，程序也会按照默认顺序进行查找课程(非必填)

Multiple = false # 是否开启多选功能(必填)
Multiple_Judge = [true,false,true] #可以填多个，必须与Course_name一一对应 (开启多选功能时必填)
Multiple_account = [[],[],[]] # 多账号抢课模式下，每个课程对应的账号列表,在每个中括号中填入账号名。可以留空，留空表示全部账号都参与抢课。(开启多选功能时必填)

#填这些东西的时候，一定要先去看学期课表，然后再填，不然可能会出错。
Teachers_name = [["老师1", "老师2",""], ["老师3", "老师4"],[]] # 每个课程对应的老师列表(候选功能)，可以填多个也可以留空，用逗号隔开，也可填入""表示不限制，以免最后没有这个老师导致抢课失败。(非必填)
Time_period = [["1-2"],[],[]] # 课程时间(节次-节次)(1-2,3-4,5-6,7-8,9-10-11,12-13)，可以填多个,也可填入""表示不限制(非必填)
Week_day = [["1","2"],[],[]] # 课程星期，可以填多个 星期一：1 星期二：2 星期三：3 星期四：4 星期五：5 星期六：6 星期日：7  ,也可填入""表示不限制(非必填)

sfym = true #是否过滤已满的课程 默认true 亦可设置为false (必填)
sfct = true #是否过滤冲突的课程 默认true 亦可设置为false (必填)
sfxx = true #是否过滤限选的课程 默认true 亦可设置为false (必填)
skxq_xx0103 = 1 #校区选择 1:曲阜 2：日照 68FD936EFC564F6E88EC852F9E8019C2：曲阜西校区

[Time]#设置定时任务
Start_time = "09:00:00" # 定时任务开始时间 (必填)
retry_time = 500 # 重试间隔，单位为毫秒 (非必填)
End_time = "09:10:00" # 定时任务结束时间，结束后自动启用END模式 (必填)
Interval = 60 # 候选定时任务间隔，单位为秒 (非必填)