[Login]
username = [ "123123",]
password = [ "123123",]

[Mode]
Number = "single"
Select = [ "Start", "End",]

[Plan]
Course_name = [ "课程1", "67865786857",]
Course_order = [ [ "1", "",], [],]
Multiple = false
Multiple_Judge = []
Multiple_account = []
Teachers_name = [ [ "老师1", "老师2", "",], [],]
Time_period = [ [ "1-2-",], [],]
Week_day = [ [ "1", "2",], [],]
sfym = false
sfct = false
sfxx = false

[Time]
Start_time = "09:00:00"
End_time = "09:10:00"
retry_time = 500
Interval = 60
